name: Build project

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  # Checks Unity license.
  checklicense:
    name: Check for UNITY_LICENSE in GitHub Secrets
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether Unity activation should be done
        id: checklicense_job
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          if [[ -n "${UNITY_LICENSE}" ]]; then
            echo "is_unity_license_set=true" >> $GITHUB_OUTPUT
          else
            echo "is_unity_license_set=false" >> $GITHUB_OUTPUT
          fi

  format_check:
    uses: ./.github/workflows/format.yaml
  
  test:
    name: Run Unity Tests
    needs: [checklicense, format_check]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: artifacts

  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: [test]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      # Checkout.
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Cache Unity Library folder.
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Build project.
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Upload artifacts.
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
